### ISSUE TITLE
Mix akvs with normal data in configmap

### ISSUE THREAD

**Issue by keriksson-rosenqvist** [SparebankenVest/akv2k8s-website#26]
I have seen that you can add multiple akvs into one k8 secret, and that you can output your akvs as a configmap. I am wondering if there's a way to have some fields in a configmap be ingested from akvs and others not, and if this can be done conditionally in a helm chart.

Example yaml file:

```
---
apiVersion: spv.no/v2beta1
kind: AzureKeyVaultSecret
metadata:
  name: aksv-ingested-value
spec:
  vault:
    name: {{ .Values.keyVault.name }}
    object:
      type: secret
      name: akvs-name
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
  namespace: {{ .Release.Namespace }}
data:
  KEY_1: key-one-value
  KEY_2: key-two-value

  {{- if .Values.some.condition.flag }}
  KEY_3: "aksv-ingested-value@azurekeyvault"
  {{- else }}
  KEY_3: key-three-default-value
  {{- end }}
---
```
Or if there is some other way to have avks overwrite some default values in a config map and be sure they're loaded after the fact. I.e. the configmap is created from yaml and then the value is replaced by an akvs secret value before ingesting into a deployment.
