### ISSUE TITLE
Is it possible to have additional fields for kubernetes.io/basic-auth?

### ISSUE THREAD

**Issue by BenjaminHerbert** [SparebankenVest/akv2k8s-website#39]
I want to create users for the ECK operator and prefill them from Azure KV by adding a secret like:

```
apiVersion: v1
kind: Secret
metadata:
  name: secret-basic-auth
type: kubernetes.io/basic-auth
stringData:
  username: rdeniro    # required field for kubernetes.io/basic-auth
  password: mypassword # required field for kubernetes.io/basic-auth
  roles: kibana_admin,ingest_admin  # optional, not part of kubernetes.io/basic-auth
```

See for further info: https://www.elastic.co/guide/en/cloud-on-k8s/master/k8s-users-and-roles.html#k8s_native_realm

I managed to fill username and password with akv2k8s. I could not find a way to do it. Is it possible to create additional entries like the **roles** field as well?
