### ISSUE TITLE
Cannot hide `/proc/1/environ` from the containers

### ISSUE THREAD

**Issue by GeorgiKarapetrov** [SparebankenVest/akv2k8s-website#51]
I would like to hide the secret values from within the container according to the [FAQ](https://akv2k8s.io/faq/#can-i-prevent-env-injected-secrets-from-being-listed-in-procpidenviron-inside-the-container).

**Chart Version:** 2.2.0
**App Version:** 1.3.1

**Sample Deployment:**
```YAML
apiVersion: apps/v1
kind: Deployment
metadata:
  ...
spec:
  ...
  template:
    metadata:
      ...
    spec:
      ...
      containers:
      ...
        securityContext:
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: <some_valid_user>
          runAsGroup: <some_valid_group>
          allowPrivilegeEscalation: false
        env:
          - name: DUMMY_SECRET
            value: "dummy@azurekeyvault"
```

**Expected behavior:**
`cat /proc/1/environ | xargs -0 -L1 |sort` does not reveal the secret values. For instance it hides secret value such as `DUMMY_SECRET=dummy@azurekeyvault`.

**Actual behavior:**
The value is actually show as in `DUMMY_SECRET=DUMMY_VALUE`.

What am I missing in my security context in order to hide the values from inside a container that has akv2k8s secrets?

By the way, this CRD is amazing.
