### ISSUE TITLE
Annotating a created secret

### ISSUE THREAD

**Issue by abudavis** [SparebankenVest/akv2k8s-website#65]
Install method: Helm/latest
Platform: Openshift 4.12

This is more like an enhancement feature.
One of our applications require an annotation on a k8s secret for it to work correctly.
Is this something that can be implemented.

Today this is how we create the secret:

```
apiVersion: spv.no/v2beta1
kind: AzureKeyVaultSecret
metadata:
  name: gitrepousersecret
  namespace: abc
spec:
  vault:
    name: vault-xyz
    object:
      name: gitrepousersecret # name of the akv object
      type: secret # akv object type
  output: # optional - only used to sync to a kubernetes secret
    secret:
      name: gitrepousersecret # kubernetes secret name
      type: kubernetes.io/basic-auth
```

This is the secret manually created with annotation "tekton.dev/git-0: 'https://github.com'"

```
kind: Secret
apiVersion: v1
metadata:
  name: gitrepousersecret
  namespace: abc
  annotations:
    tekton.dev/git-0: 'https://github.com'
data:
  password: MGY1Q1ZjU5OWQyYjA3ZDg1ZlMTg0ZjhjZGU2NTUyM0ZjBmNg==
  username: dGlWdGh1Yg==
type: kubernetes.io/basic-auth
```
